#+TITLE:  Librairie =scipy=
#+AUTHOR: Xavier Garrido
#+DATE:   20/02/2020
#+OPTIONS: toc:nil ^:{}
#+LATEX_HEADER: \setcounter{chapter}{4}

* Higgs en \gamma\gamma

Le 4 juillet 2012, les expériences ATLAS et CMS, menées au Grand collisionneur de hadrons (LHC), ont
annoncé qu’elles avaient toutes deux observé une nouvelle particule dont la masse se situait dans la
région des 126 GeV. Cette particule présente des caractéristiques compatibles avec celles du boson
de Higgs prédit par le Modèle standard. Le boson de Higgs, tel que le décrit ce modèle, est la
manifestation la plus simple du mécanisme de Brout-Englert-Higgs qui permet, notamment, d'expliquer
théoriquement la masse des particules élémentaires.

Le 8 octobre 2013, le prix Nobel de physique a été attribué conjointement à François Englert et à
Peter Higgs « pour la découverte théorique d’un mécanisme contribuant à notre compréhension de
l’origine de la masse des particules subatomiques, une théorie qui s’est confirmée récemment,
lorsque les expériences ATLAS et CMS, menées au Grand collisionneur de hadrons du CERN, ont
découvert la particule prédite. »

Pour détecter le boson de Higgs, les physiciens des expériences ATLAS et CMS étudient notamment la
désintégration de cette particule en une paire de photons \gamma. On peut alors mesurer le nombre
d'événements comprenant uniquement deux photons et le comparer à un modèle dans lequel le boson de
Higgs n'existe pas. Une différence significative entre données et modèle signe alors l'existence
d'une nouvelle particule.

Les données [[https://owncloud.lal.in2p3.fr/index.php/s/42zx4JmrXmn47MA][=higgs-gg.csv=]] représentent les résultats obtenus par l'expérience ATLAS au cours des
années 2011/2012. Dans ce fichier, figure en première colonne l'énergie des deux photons exprimée en
GeV, le nombre de paire di-photons observées en deuxième colonne et l'incertitude sur ce nombre en
troisième colonne. Dans cet exercice, on cherche à reproduire la figure ci-dessous publiée dans
[[https://arxiv.org/abs/1207.7214][/Phys. Rev. Letter B716/ (2012)]] et annonçant la découverte d'une nouvelle particule.

[[file:figures/higgs_gg.pdf]]

- Représenter le nombre d'événements di-photons en fonction de l'énergie. On oubliera pas
  d'intituler les axes de cette figure afin d'y faire figurer toute information pertinente.

- Représenter le modèle suivant
  #+BEGIN_SRC latex
    \begin{align*}
      y_\text{modèle} = -1.668\,10^{-2}x^3 + 7.697x^2 + -1208.9x + 6.527\,10^{4}
    \end{align*}
  #+END_SRC
  Calculer la valeur du $\chi^2$ où

  #+BEGIN_SRC latex
    \begin{align*}
      \chi^2=\sum_i\frac{\left(y_i-y_\text{modèle}(x_i)\right)^2}{\sigma_{y_i}^2}
    \end{align*}
  #+END_SRC

  et la diviser par le nombre de degrés de liberté qui correspond au nombre de points expérimentaux
  moins le nombre de paramètres du modèle. Pour information, une valeur de \chi^{2}/ndof voisine de
  1 démontre l'adéquation statistique entre données et modèle.

- Représenter dans une sous figure, la différence entre le modèle et les données puis normaliser
  cette différence par rapport à l'erreur sur chacun des points expérimentaux. Une découverte en
  physique des particules est établie lorsque le nombre d'écart-type \sigma entre données
  expérimentales et modèle est supérieur à 5. Isoler graphiquement les points expérimentaux pour
  lesquels la déviation est supérieure à 3\sigma. Déterminer enfin la valeur maximale de cette
  déviation en nombre de \sigma et affirmer ou non avoir découvert le boson de Higgs. Le cas
  échéant, donner la masse de cette particule.

** Correction                                                   :correction:

#+BEGIN_SRC python :tangle scripts/higgs.py :results output
  import numpy as np
  data = np.loadtxt("./data/higgs-gg.csv", delimiter=",")

  x, y, yerr = data.T

  import matplotlib.pyplot as plt

  grid = plt.GridSpec(4, 1, hspace=0, wspace=0)

  main = plt.subplot(grid[0:3], xticklabels=[])
  main.errorbar(x, y, yerr=yerr, fmt=".k", label="ATLAS data")
  main.set_ylabel(r"Nombre d'événements $H\to\gamma\gamma$")

  # "Theoritical model" = 4th order polynomial
  def model(x, parameters=[6.527e4, -1208.9, 7.697, -1.668e-2]):
      y = 0.0
      for i, p in enumerate(parameters):
          y += p*np.power(x, i)
      return y

  xmodel = np.linspace(105, 160, 100)
  main.plot(xmodel, model(xmodel), "-r", label="modèle polynomial")

  # Plot deviation
  sub = plt.subplot(grid[3])
  dev = (y - model(x))/yerr
  sub.errorbar(x, dev, fmt=".k")
  sub.set_ylabel(r"$\frac{y-y_\mathrm{modèle}}{\sigma}$ [$\sigma$]")
  sub.set_xlabel(r"$m_{\gamma\gamma}$ [MeV]")

  # Calculate chi2/ndf and add it to legend
  chi2n = np.sum(dev**2)/(len(dev)-4)
  main.plot([], [], linestyle="None", label=r"$\chi^2/$ndf = {0:.2f}".format(chi2n))
  main.legend()

  mask = (dev > 3)
  sub.scatter(x[mask], dev[mask], edgecolors="red", c="none", s=100)

  print("Masse du boson de Higgs = {} GeV".format(x[mask][0]))

  # Fit with a 4th order polynomial
  parameters = np.polyfit(x, y, 3)
  fit = np.poly1d(parameters)
  print("Best parameters : " + str(parameters))

  plt.show()
#+END_SRC

#+RESULTS:
: Masse du boson de Higgs = 126.0 GeV
: Best parameters : [ -1.66824264e-02   7.69724379e+00  -1.20891766e+03   6.52746509e+04]

[[file:figures/mpl_higgs_gg.pdf]]

[[https://owncloud.lal.in2p3.fr/index.php/s/0u7iKiSksnGQrGJ][Télécharger la solution]]

* ODE

https://apmonitor.com/pdc/index.php/Main/SimulateHIV

https://sam-dolan.staff.shef.ac.uk/mas212/notebooks/ODE_Example.html

https://ipython-books.github.io/123-simulating-an-ordinary-differential-equation-with-scipy/
